version: '3.8'

services:
  springboot:
    image: jobcho6320/floud:latest
    ports:
      - "80:80"
    depends_on:
      - redis
    build:
      context: ../../
      dockerfile: ./Dockerfile
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    command: redis-server
